# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/tolkogroup/public_html/
#     - /bin/cp -r frontend/dist/* $DEPLOYPATH
#     - /bin/cp -r api/* $DEPLOYPATH

###################################################################

# deployment:
#   tasks:
#     - export FRONTEND_DEPLOYPATH=/home/tolkogroup/public_html/
#     - export API_DEPLOYPATH=/home/tolkogroup/public_html/api/
#     - mkdir -p $FRONTEND_DEPLOYPATH
#     - mkdir -p $API_DEPLOYPATH
#     - /bin/cp -r frontend/dist/* $FRONTEND_DEPLOYPATH
#     - /bin/cp -r api/* $API_DEPLOYPATH

###################################################################

---
deployment:
  tasks:
    - echo "Iniciando el despliegue..."

    - echo "Instalando NVM..."
    - 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash'

    - echo "Cargando NVM..."
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'

    - echo "Instalando y utilizando Node.js 20.14.0..."
    - 'nvm install 20.14.0'
    - 'nvm use 20.14.0'

    - echo "Verificando la versión de Node.js..."
    - 'node -v'
    - 'which node'

    - echo "Estableciendo rutas de despliegue..."
    - export FRONTEND_DEPLOYPATH=/home/tolkogroup/public_html/
    - export API_DEPLOYPATH=/home/tolkogroup/public_html/api/

    - echo "Estableciendo opciones de memoria para Node.js..."
    - export NODE_OPTIONS="--max-old-space-size=4096"

    # Compilar y desplegar el frontend
    - echo "Compilando el frontend..."
    - 'cd frontend && npm install && npm run build'
    - 'cd ..'

    - echo "Creando directorio de despliegue del frontend..."
    - 'mkdir -p $FRONTEND_DEPLOYPATH'

    - echo "Copiando archivos del frontend..."
    - '/bin/cp -r frontend/dist/* $FRONTEND_DEPLOYPATH'

    # Compilar y desplegar la API
    - echo "Compilando la API..."
    - 'cd api && npm install && npm run build'
    - 'cd ..'

    - echo "Creando directorio de despliegue de la API..."
    - 'mkdir -p $API_DEPLOYPATH'

    - echo "Copiando archivos de la API..."
    - '/bin/cp -r api/* $API_DEPLOYPATH'

    - echo "Despliegue completado."
