# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/tolkogroup/public_html/
#     - /bin/cp -r frontend/dist/* $DEPLOYPATH
#     - /bin/cp -r api/* $DEPLOYPATH

# deployment:
#   tasks:
#     - export FRONTEND_DEPLOYPATH=/home/tolkogroup/public_html/
#     - export API_DEPLOYPATH=/home/tolkogroup/public_html/api/
#     - mkdir -p $FRONTEND_DEPLOYPATH
#     - mkdir -p $API_DEPLOYPATH
#     - /bin/cp -r frontend/dist/* $FRONTEND_DEPLOYPATH
#     - /bin/cp -r api/* $API_DEPLOYPATH

deployment:
  tasks:
    # - echo "Compilando el frontend..."
    - cd frontend
    - npm install
    - npm run build
    - export FRONTEND_DEPLOYPATH=/home/tolkogroup/public_html/
    - mkdir -p $FRONTEND_DEPLOYPATH
    - /bin/cp -r dist/* $FRONTEND_DEPLOYPATH
    - cd ..

    # - echo "Compilando la API..."
    - cd api
    - npm install # Si tu API utiliza npm, de lo contrario ajusta este comando según sea necesario
    - npm run build # Si tu API tiene un paso de compilación, de lo contrario omite este comando
    - export API_DEPLOYPATH=/home/tolkogroup/public_html/api/
    - mkdir -p $API_DEPLOYPATH
    - /bin/cp -r * $API_DEPLOYPATH
    - cd ..
